name: studentchilik
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  sizer: ^2.0.15
  google_fonts: ^3.0.1
  firebase_core: ^1.17.1
  firebase_auth: ^3.3.19
  flutter_svg: ^1.1.0

dev_dependencies: 
  flutter_lints: ^2.0.0
  lints: 2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  fonts:
    - family: CircularStd
      fonts:
        - asset: assets/fonts/circular_std.ttf
          weight: 500
        - asset: assets/fonts/circular_std_bold.ttf
          weight: 600
        - asset: assets/fonts/circular_std_black.ttf
          weight: 700
  assets:
    - assets/images/calculator.svg
    - assets/images/home.svg
    - assets/images/user.svg
    - assets/images/shopping-cart.svg

  uses-material-design: true


